import streamlit as st
import requests
from bs4 import BeautifulSoup
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import datetime
import tempfile

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="SSC Pro Calculator", page_icon="🚀", layout="centered")

# Custom CSS for Mobile View
st.markdown("""
    <style>
    .main-title { font-size: 28px; font-weight: 900; color: #1E3A8A; text-align: center; }
    .score-card { background-color: #DBEAFE; padding: 15px; border-radius: 10px; text-align: center; border: 2px solid #93C5FD; }
    .score-text { font-size: 35px; font-weight: 900; color: #1E40AF; }
    .stButton>button { background-color: #2563EB; color: white; font-weight: bold; border-radius: 8px; padding: 10px; width: 100%; }
    .stButton>button:hover { background-color: #1D4ED8; }
    </style>
""", unsafe_allow_html=True)

# --- PDF GENERATOR FUNCTION ---
def create_pdf(name, exam_name, score, c, w, b):
    pdf = FPDF()
    pdf.add_page()
    
    # Title
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(30, 58, 138)
    pdf.cell(200, 15, txt="SSC OFFICIAL SCORECARD", ln=True, align='C')
    
    pdf.set_font("Arial", '', 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(200, 10, txt=f"Date Generated: {datetime.date.today()}", ln=True, align='C')
    pdf.line(10, 35, 200, 35)
    
    # Candidate Details
    pdf.set_font("Arial", 'B', 14)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)
    pdf.cell(100, 10, txt=f"Candidate Name: {name.upper()}", ln=True)
    pdf.cell(100, 10, txt=f"Exam Type: {exam_name}", ln=True)
    
    # Score Highlight
    pdf.ln(10)
    pdf.set_font("Arial", 'B', 18)
    pdf.set_text_color(0, 128, 0)
    pdf.cell(200, 15, txt=f"FINAL SCORE: {score} Marks", ln=True, align='C')
    
    # Details
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)
    pdf.cell(100, 10, txt=f"Correct Answers (+): {c}", ln=True)
    pdf.set_text_color(255, 0, 0)
    pdf.cell(100, 10, txt=f"Wrong Answers (-): {w}", ln=True)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(100, 10, txt=f"Unattempted: {b}", ln=True)
    
    # Accuracy
    accuracy = round((c / (c + w)) * 100, 2) if (c+w) > 0 else 0
    pdf.set_text_color(0, 0, 255)
    pdf.cell(100, 10, txt=f"Accuracy: {accuracy}%", ln=True)
    
    pdf.line(10, 130, 200, 130)
    pdf.set_font("Arial", 'I', 10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(200, 10, txt="Generated by Pro SSC Calculator", ln=True, align='C')
    
    # Save PDF
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf.output(temp_file.name)
    return temp_file.name

# --- SSC SCRAPING LOGIC ---
def calculate_ssc_marks(url, pos_mark, neg_mark):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }
    try:
        res = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(res.text, 'html.parser')
        
        blocks = soup.find_all('div', class_='question-pnl')
        if not blocks:
            blocks = soup.find_all('table', class_='menu-tbl')
            
        if not blocks:
            return None, "Error: HTML format change ho gaya hai ya URL invalid hai."

        correct, wrong, blank = 0, 0, 0
        
        for block in blocks:
            # Get Right Answer
            right_ans_elem = block.find('td', class_='rightAns')
            if not right_ans_elem: continue
            right_ans = right_ans_elem.text.strip()[0]
            
            # Get Chosen Option
            chosen_ans = "--"
            tds = block.find_all('td')
            for i, td in enumerate(tds):
                if "Chosen Option" in td.text:
                    if i + 1 < len(tds):
                        chosen_ans = tds[i+1].text.strip()
                    break
            
            # Compare
            if chosen_ans in ["--", ""]:
                blank += 1
            elif chosen_ans == right_ans:
                correct += 1
            else:
                wrong += 1
                
        score = (correct * pos_mark) - (wrong * neg_mark)
        return (correct, wrong, blank, round(score, 2)), "Success"
        
    except Exception as e:
        return None, str(e)


# --- MAIN APP UI ---
st.markdown('<p class="main-title">🚀 Pro SSC Calculator</p>', unsafe_allow_html=True)
st.write("Enter your official Answer Key URL to check your real score.")

# Inputs
url = st.text_input("🔗 Paste Answer Key URL Here:")
name = st.text_input("👤 Enter Your Name:")

exam_mapping = {
    "SSC CGL/CHSL/MTS (+2, -0.5)": (2.0, 0.5),
    "SSC Mains Tier 2 (+3, -1)": (3.0, 1.0),
    "SSC GD Constable (+1, -0.25)": (1.0, 0.25)
}
exam_type = st.selectbox("🎯 Select Exam Pattern:", list(exam_mapping.keys()))

if st.button("Calculate My Score"):
    if url and name:
        with st.spinner("Extracting data from SSC Server..."):
            pos_m, neg_m = exam_mapping[exam_type]
            result, msg = calculate_ssc_marks(url, pos_m, neg_m)
            
            if result:
                c, w, b, total_score = result
                
                # Show Score Card
                st.markdown(f"""
                <div class="score-card">
                    <p style="margin:0; color:#4B5563; font-weight:bold;">{name.upper()}'S FINAL SCORE</p>
                    <p class="score-text">{total_score}</p>
                </div>
                """, unsafe_allow_html=True)
                
                st.write("---")
                
                # Metrics Row
                col1, col2, col3 = st.columns(3)
                col1.metric("✅ Correct", c)
                col2.metric("❌ Wrong", w)
                col3.metric("⚠️ Blank", b)
                
                # Plotly Chart
                st.subheader("📊 Performance Chart")
                df = pd.DataFrame({
                    "Status": ["Correct", "Wrong", "Unattempted"],
                    "Count": [c, w, b]
                })
                fig = px.pie(df, values='Count', names='Status', hole=0.5,
                             color='Status', color_discrete_map={'Correct':'#22C55E', 'Wrong':'#EF4444', 'Unattempted':'#9CA3AF'})
                fig.update_layout(margin=dict(t=0, b=0, l=0, r=0), height=300)
                st.plotly_chart(fig, use_container_width=True)
                
                # Accuracy Warning
                accuracy = (c / (c + w)) * 100 if (c+w) > 0 else 0
                if accuracy < 70:
                    st.error(f"🤖 AI Alert: Your accuracy is {accuracy:.1f}%. Negative marks impacted your score.")
                else:
                    st.success(f"🤖 AI Alert: Great accuracy of {accuracy:.1f}%!")
                
                # PDF Download Button
                pdf_path = create_pdf(name, exam_type, total_score, c, w, b)
                with open(pdf_path, "rb") as file:
                    st.download_button(
                        label="📥 Download Marksheet PDF",
                        data=file,
                        file_name=f"{name.replace(' ', '_')}_Scorecard.pdf",
                        mime="application/pdf"
                    )
                    
            else:
                st.error(f"Failed! Reason: {msg}")
    else:
        st.warning("Please enter both URL and Name!")
