import streamlit as st
import pandas as pd
import plotly.express as px
from fpdf import FPDF
import datetime

# --- PAGE CONFIGURATION (For Mobile Friendly Look) ---
st.set_page_config(page_title="Pro Score Calculator", page_icon="🚀", layout="centered")

# Custom CSS for Mobile Styling
st.markdown("""
<style>
    .big-font {font-size:30px !important; font-weight: bold; color: #FF4B4B;}
    .card {background-color: #f0f2f6; padding: 20px; border-radius: 10px; box-shadow: 2px 2px 5px grey;}
</style>
""", unsafe_allow_html=True)

# --- 1. PDF SCORECARD GENERATOR ---
def create_pdf(name, score, correct, wrong, total_q):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="SSC Exam Official Scorecard", ln=True, align='C')
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(200, 10, txt=f"Date: {datetime.date.today()}", ln=True, align='C')
    pdf.cell(200, 10, txt="-"*50, ln=True, align='C')
    
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(100, 10, txt=f"Candidate Name: {name}", ln=True)
    pdf.cell(100, 10, txt=f"Total Score: {score} Marks", ln=True)
    
    pdf.set_font("Arial", '', 12)
    pdf.cell(100, 10, txt=f"Correct Answers: {correct}", ln=True)
    pdf.cell(100, 10, txt=f"Wrong Answers: {wrong}", ln=True)
    pdf.cell(100, 10, txt=f"Accuracy: {round((correct/(correct+wrong))*100, 2)}%", ln=True)
    
    pdf.cell(200, 10, txt="-"*50, ln=True, align='C')
    pdf.cell(200, 10, txt="Generated by ProScore Calculator (www.yourwebsite.com)", ln=True, align='C')
    
    # Save to a temporary file
    pdf_filename = "Scorecard.pdf"
    pdf.output(pdf_filename)
    return pdf_filename

# --- 2. FIREBASE & SHEETS LOGIC (Mockup) ---
def save_to_database(name, score, category):
    # Yahan tumhara Firebase aur Google Sheets API ka code aayega
    # For now, hum assume kar rahe hain database me chala gaya
    return True

# --- 3. MAIN APP UI ---
st.markdown('<p class="big-font">SSC Rank & Score Analyzer 🚀</p>', unsafe_allow_html=True)
st.write("India's most advanced Exam Analyzer.")

# UI Inputs
with st.container():
    url = st.text_input("🔗 Paste Your Answer Key URL Here:")
    col1, col2 = st.columns(2)
    name = col1.text_input("👤 Your Name (For Scorecard)")
    category = col2.selectbox("🏷️ Category", ["UR", "OBC", "EWS", "SC", "ST"])

if st.button("Generate My Results & Rank", use_container_width=True):
    if url and name:
        with st.spinner("Decoding your answer key and calculating rank..."):
            # Mock Data (Yahan actual web scraping ka logic aayega)
            correct_ans = 65
            wrong_ans = 15
            unattempted = 20
            total_score = (correct_ans * 2) - (wrong_ans * 0.5)
            
            # Save to Database
            save_to_database(name, total_score, category)
            
            # --- RESULTS SECTION ---
            st.success("Analysis Complete!")
            st.markdown(f"### 🎉 Your Score: {total_score} Marks")
            
            # Metric Cards
            c1, c2, c3 = st.columns(3)
            c1.metric(label="✅ Correct", value=correct_ans)
            c2.metric(label="❌ Wrong", value=wrong_ans, delta="-7.5 marks", delta_color="inverse")
            c3.metric(label="⚠️ Unattempted", value=unattempted)
            
            # --- UNIQUE FEATURE: VISUAL GRAPHS ---
            st.subheader("📊 Performance Analytics")
            df = pd.DataFrame({
                "Status": ["Correct", "Wrong", "Unattempted"],
                "Count": [correct_ans, wrong_ans, unattempted]
            })
            fig = px.pie(df, values='Count', names='Status', color='Status',
                         color_discrete_map={'Correct':'green', 'Wrong':'red', 'Unattempted':'grey'})
            # Mobile friendly size
            fig.update_layout(width=350, height=350)
            st.plotly_chart(fig, use_container_width=True)
            
            # --- UNIQUE FEATURE: TUKKA ANALYZER ---
            accuracy = (correct_ans / (correct_ans + wrong_ans)) * 100
            if accuracy < 70:
                st.warning("🤖 AI Analysis: Aapki accuracy thodi kam hai. Negative marking ne aapke score ko kafi giraya hai.")
            else:
                st.info("🤖 AI Analysis: Great Accuracy! Aapne tukke kam maare hain.")

            # --- GENERATE PDF SCORECARD ---
            pdf_file = create_pdf(name, total_score, correct_ans, wrong_ans, 100)
            
            with open(pdf_file, "rb") as file:
                st.download_button(
                    label="📥 Download Scorecard PDF",
                    data=file,
                    file_name=f"{name}_Scorecard.pdf",
                    mime="application/pdf",
                    use_container_width=True
                )
            
            # --- WHATSAPP SHARE ---
            msg = f"My SSC Score is {total_score}. Check your rank here: www.yourwebsite.com"
            wa_link = f"https://api.whatsapp.com/send?text={msg}"
            st.markdown(f'[🟢 Share on WhatsApp]({wa_link})', unsafe_allow_html=True)
            
    else:
        st.error("Please enter URL and Name first!")
